version: '3.7'

services:
  redis:
    image: redis:6.2.6-alpine
    ports:
      - '6379:6379'
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    image: ${SERVER_IMAGE_TAG}
    restart: 'no'
    depends_on:
      - redis
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    environment:
      - SERVER_HOST=${CLIENT_SERVER_HOST}
      - SERVER_PORT=${CLIENT_SERVER_PORT}
    image: ${CLIENT_IMAGE_TAG}
    restart: 'no'
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
